#!/usr/bin/env python3
"""Emit weak stubs for the symbols a fuzz target's link left undefined.

Input: the linker's "Undefined symbols" diagnostics on stdin (ld64 or GNU ld).
Output (stdout): C source with one weak definition per symbol. A symbol that
any host-source declares `extern` without a parameter list is data and gets a
zeroed 64 KB backing array; everything else is a function returning 0, which
is ABI-safe for every integer/pointer/void return on the hosts we build on.

Strong definitions in common/stubs.c or the harness always win over these, so
anything whose behaviour matters to a harness is written by hand there.

Usage: gen_weak_stubs.py <hostsrc_dir> < link_errors.txt > autostubs.c
"""
import os
import re
import sys

hostsrc = sys.argv[1]
text = sys.stdin.read()
syms = set(re.findall(r'^\s+"_?([A-Za-z_][A-Za-z0-9_]*)", referenced from', text, re.M))
syms |= set(re.findall(r"undefined reference to `([A-Za-z_][A-Za-z0-9_]*)'", text))

decls = ""
for name in os.listdir(hostsrc):
    if name.endswith((".h", ".c")):
        with open(os.path.join(hostsrc, name), "rb") as f:
            decls += f.read().decode("latin-1") + "\n"

print("/* GENERATED by fuzz/gen_weak_stubs.py -- do not edit. */")
for s in sorted(syms):
    is_data = re.search(r"\bextern\b[^;(]*\b%s\b\s*(\[[^\]]*\])?\s*;" % re.escape(s), decls)
    if is_data:
        print("__attribute__((weak, aligned(64))) unsigned char %s[65536];" % s)
    else:
        print("__attribute__((weak)) long %s(void) { return 0; }" % s)
