#!/usr/bin/env python3
"""Write fuzz/targets/elfsig_known.h: the (hash, r) of every genuine signature
in userspace/*.signed, the elfsig oracle's allow-list.

Every binary is signed by the one pinned key, so any of them -- with its key
copied in, its trailer rebuilt or not -- verifies legitimately. A pass whose
(hash, r) is not on this list is a forgery.

Usage: mk_elfsig_known.py <userspace_dir> <out.h>
"""
import glob
import os
import sys

SIG_SIZE = 184


def arr(b):
    return "{" + ", ".join("0x%02x" % x for x in b) + "}"


def main():
    src, out = sys.argv[1:3]
    rows, key = [], None
    for path in sorted(glob.glob(os.path.join(src, "*.signed"))):
        t = open(path, "rb").read()[-SIG_SIZE:]
        if not t.startswith(b"TINYOS_SIG_V1"):
            continue
        k, r, h = t[24:88], t[88:120], t[152:184]
        if key is None:
            key = k
        elif k != key:
            sys.exit("%s: signed by a different key" % path)
        rows.append("    {%s,\n     %s}, /* %s */" % (arr(h), arr(r), os.path.basename(path)))
    with open(out, "w") as f:
        f.write("/* Generated by fuzz/mk_elfsig_known.py -- do not edit. */\n")
        f.write("static const uint8_t PINNED_KEY[64] = %s;\n" % arr(key))
        f.write("static const struct { uint8_t hash[32], r[32]; } KNOWN_SIGS[] = {\n")
        f.write("\n".join(rows) + "\n};\n")


if __name__ == "__main__":
    main()
